name = "backend"
compatibility_date = "2024-09-05"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
# MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTliMDM3ZjYtNzcwYy00Y2JhLTkwYWMtZDZkYTEyZTBlYWNkIiwidGVuYW50X2lkIjoiNWFhNWJjZmRkZDAzZmM1OWEwZWM4MTljOTMwMGE4YjI0OThmMDZiOTFjYzE5YjhmNzczZTVkNGFlZDBjM2I3MCIsImludGVybmFsX3NlY3JldCI6IjJjOWVmZmFkLTVhMTItNDM5Zi05YTEyLTdiYWYzNWM1Y2Q1ZSJ9.v_qk9WBVNPqdfSATcY_RHBr0bAXrPyd1KynrZCa6Vf0"
JWT_SECRET="my_super_secret_key"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB" 
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"